export const loadingCaptions = [
    "Summoning the pixels...",
    "Fetching art ingredients...",
    "Drawing stick figures...",
    "Applying digital paint...",
    "Awakening AI artist...",
    "Artificially imagining...",
    "Painting in binary...",
    "Brewing pixel potion...",
    "Coding a masterpiece...",
    "Crafting with 0s & 1s...",
    "Adding a bit more AI...",
    "Decoding your desire...",
    "Mimicking Monet...",
    "Rendering reality...",
    "Chasing digital dreams...",
    "Inventing new colors...",
    "Running the matrix...",
    "Stirring up pixels...",
    "Creating visual magic...",
    "Baking a bytecake...",
    "Sculpting in silicon...",
    "Sifting through bits...",
    "Conjuring coded canvas...",
    "Pixel party in progress...",
    "Dreaming in RGB...",
    "Turning data into art...",
    "Whisking up wonder...",
    "Building beauty bit by bit...",
    "Imagining the inconceivable...",
    "Beaming up bitmap...",
    "Nudging neural networks...",
    "Pixel whisperer at work...",
    "Wrestling with resolution...",
    "Bytes for breakfast...",
    "Pixels in pyjamas...",
    "404: Art not found...",
    "AI doing push-ups...",
    "CPU doing crunches...",
    "Wait, where's my paintbrush?",
    "Defragging the da Vinci...",
    "Compiling creative chaos...",
    "RGB or not RGB...",
    "Lost in layers...",
    "Assembling arty atoms...",
    "Teaching AI aesthetics...",
    "Art loading...hopefully...",
    "Digital daydreaming underway...",
    "Initiating creative infinity...",
    "Invoking image incantations...",
    "Optimizing optical illusions...",
    "AI is doodling...",
    "Polishing pixels...",
    "Oops, dropped the pixels!",
    "Rebooting Rembrandt...",
    "Buffering brushstrokes...",
    "Artificially Imagining...stuff.",
    "Picasso processing power...",
    "Stirring up the surreal...",
    "Multitasking in monochrome...",
    "1s, 0s, ready, go!",
    "Oh look, another pixel...",
    "Image, or not to image...",
    "Gathering imaginary paint...",
    "Don't mind the AI...",
    "Just dozing off here...",
    "Got lost in coding...",
    "Becoming Van Gogh...slowly.",
    "AI's daydreaming again...",
    "Pixels, assemble!",
    "Fumbling through filters...",
    "Cooking up colors...",
    "This art won't art...",
    "Deciding on dithering...",
    "Ready, set, image!",
    "Misplacing the matrix...",
    "Counting digital sheep...",
    "Bargaining with bytes...",
    "Any minute now...",
    "Please hold, processing Picasso...",
    "Stuck on surrealism...",
    "Coloring outside the lines...",
    "In pixel purgatory...",
    "Do you even art, bro?",
    "Pixels on a coffee break...",
    "Scrambling the spectrum...",
    "Caught in a color conundrum...",
    "Still can't find Waldo...",
    "Making AI great again...",
    "Resolving a resolution riot...",
    "Your art is on backorder...",
    "Brushstrokes buffering, brace yourself...",
    "Pacifying pixel panic...",
    "Working smarter, not harder...",
    "Rome wasn't painted in a day...",
    "Let me guess, another image?",
    "Unleashing unicorn colors...",
    "In case of art failure, break glass...",
    "Now baking binary brownies...",
    "Creating more than meets the AI...",
    "When in doubt, reboot...",
    "Trust me, I'm an AI...",
    "Have you tried turning it off and on again?",
    "Doing some digital doodling...",
    "This is harder than it pixels...",
    "Not now, I'm rendering...",
    "Binary or not binary...",
    "Pixel whisperer on vacation...",
    "I promise, no stick figures...",
    "Buffering...but with style.",
    "Teaching an AI to draw...",
    "Making the bits fit...",
    "Just another manic Monday...",
    "Running on caffeinated code...",
    "Computing in Comic Sans...",
    "May contain traces of pixels...",
    "Images loading...honest.",
    "Struggling with stick figures...",
    "Waiting for inspiration to strike...",
    "Don't rush art...",
    "Fiddling with filters...",
    "For want of a pixel...",
    "Pixelated procrastination in progress...",
    "Please wait, Picasso in process...",
    "It's not a bug, it's a feature!",
    "Brewing up some bitmap...",
    "Recycling unused pixels...",
    "I'm more of an Impressionist...",
    "Go make a coffee...",
    "Keeping it abstract...",
    "Now you see it, now you don't...",
    "Adjusting the artitude...",
    "Spilling the paint...",
    "Color crisis imminent...",
    "One pixel at a time...",
    "Loading creativity, please wait...",
    "Hunting down hues...",
    "Coloring inside the lines...",
    "Searching for the perfect pixel...",
    "Art is 1% inspiration, 99% perspiration.",
    "Blink and you'll miss it...",
    "Running low on blue...",
    "This is why we can't have nice things...",
    "Working on my masterpiece...",
    "Art harder, AI!",
    "Art doesn't follow a timetable...",
    "Taming rogue pixels...",
    "Doing some deep image thinking...",
    "Pixel perfect...almost.",
    "Paint drying simulation...",
    "Waiting for the muse...",
    "Making every pixel count...",
    "Solving for X, where X=art...",
    "Between a rock and an art place...",
    "Who let the pixels out?",
    "Adding some artificial artistry...",
    "Feeling kind of sketchy...",
    "Caught in a color quandary...",
    "Now serving number 256...",
    "Bytes and bits and lots of grits...",
    "Turning code into 'could'...",
  ];